"""Tests for the parts of the CLI that transform data rather than print it."""

from __future__ import annotations

from datetime import date

import pytest
import yaml

from sos.cli import _render_config_yaml, _yaml_scalar, last_complete_month, shift_months
from sos.config import ConfigError, _config_from_dict


# --------------------------------------------------------------------------
# `sos init` round-trip
# --------------------------------------------------------------------------


def _roundtrip(brand: str, competitors: list, url: str = "", market: str = "US") -> dict:
    text = _render_config_yaml(brand, url, competitors, market, 2840, "en")
    return yaml.safe_load(text)


@pytest.mark.parametrize(
    "brand",
    [
        "Acme",
        "Acme #1",              # everything after # would become a comment
        "Foo: Bar",             # unquoted colon is a parse error
        "Null",                 # YAML would load this as None
        "Yes",                  # ...and this as True
        "123",                  # ...and this as an int
        "O'Brien",
        'The "Best" Co',
        "Café Ø",
        "- leading dash",
        "{braces}",
    ],
)
def test_prompted_brand_names_survive_a_round_trip(brand):
    """Whatever someone types must load back as the same string."""
    loaded = _roundtrip(brand, ["Globex"])

    assert loaded["own_brand"]["name"] == brand
    assert isinstance(loaded["own_brand"]["name"], str)


def test_prompted_competitor_names_survive_a_round_trip():
    loaded = _roundtrip("Acme", ["Foo: Bar", "Globex #2", "Null"])

    assert [c["name"] for c in loaded["competitors"]] == ["Foo: Bar", "Globex #2", "Null"]


def test_a_generated_config_passes_validation():
    text = _render_config_yaml("Foo: Bar", "https://x.test/?a=1&b=2", ["Acme #1", "Null"], "US", 2840, "en")
    config = _config_from_dict(yaml.safe_load(text))

    assert config.own_brand.name == "Foo: Bar"
    assert config.own_brand.url == "https://x.test/?a=1&b=2"
    assert [b.name for b in config.competitors] == ["Acme #1", "Null"]


def test_the_generated_config_keeps_its_explanatory_comments():
    text = _render_config_yaml("Acme", "", ["Globex"], "US", 2840, "en")

    assert "# Generated by `sos init`" in text
    assert "# Set `ambiguous: true`" in text


def test_yaml_scalar_leaves_ordinary_values_unquoted():
    assert _yaml_scalar("acme") == "acme"
    assert _yaml_scalar("Foo: Bar").startswith(("'", '"'))


# --------------------------------------------------------------------------
# Date handling
# --------------------------------------------------------------------------


def test_the_current_month_is_never_requested():
    """Google Ads has no data for a month that hasn't finished."""
    assert last_complete_month(date(2026, 8, 1)) == date(2026, 7, 1)
    assert last_complete_month(date(2026, 8, 31)) == date(2026, 7, 1)
    assert last_complete_month(date(2026, 1, 15)) == date(2025, 12, 1)


def test_shift_months_crosses_year_boundaries():
    assert shift_months(date(2026, 1, 1), -1) == date(2025, 12, 1)
    assert shift_months(date(2026, 1, 1), -13) == date(2024, 12, 1)
    assert shift_months(date(2025, 12, 1), 1) == date(2026, 1, 1)
    assert shift_months(date(2026, 7, 1), -47) == date(2022, 8, 1)
