"""Tests for the parts of the CLI that transform data rather than print it."""

from __future__ import annotations

import subprocess
import sys
from datetime import date
from pathlib import Path

import click
import pytest
import yaml

import sos
from sos.cli import (
    BACKFILL_MONTHS,
    REEXEC_ENV_VAR,
    _BrandDraft,
    _pull,
    _pull_status,
    _render_config_yaml,
    _resolve_range,
    _source_checkout,
    _split_keywords,
    _update_code,
    _yaml_scalar,
    last_complete_month,
    shift_months,
)
from sos.config import ConfigError, _config_from_dict, keyword_parity_warnings


# --------------------------------------------------------------------------
# `sos init` round-trip
# --------------------------------------------------------------------------


def _draft(name: str, keywords: list = None, ambiguous: bool = False, url: str = "") -> _BrandDraft:
    return _BrandDraft(
        name=name,
        keywords=keywords if keywords is not None else [name.lower()],
        ambiguous=ambiguous,
        url=url,
    )


def _roundtrip(brand: str, competitors: list, url: str = "", market: str = "US") -> dict:
    text = _render_config_yaml(
        _draft(brand, url=url), [_draft(c) for c in competitors], market, 2840, "en"
    )
    return yaml.safe_load(text)


@pytest.mark.parametrize(
    "brand",
    [
        "Acme",
        "Acme #1",              # everything after # would become a comment
        "Foo: Bar",             # unquoted colon is a parse error
        "Null",                 # YAML would load this as None
        "Yes",                  # ...and this as True
        "123",                  # ...and this as an int
        "O'Brien",
        'The "Best" Co',
        "Café Ø",
        "- leading dash",
        "{braces}",
    ],
)
def test_prompted_brand_names_survive_a_round_trip(brand):
    """Whatever someone types must load back as the same string."""
    loaded = _roundtrip(brand, ["Globex"])

    assert loaded["own_brand"]["name"] == brand
    assert isinstance(loaded["own_brand"]["name"], str)


def test_prompted_competitor_names_survive_a_round_trip():
    loaded = _roundtrip("Acme", ["Foo: Bar", "Globex #2", "Null"])

    assert [c["name"] for c in loaded["competitors"]] == ["Foo: Bar", "Globex #2", "Null"]


def test_a_generated_config_passes_validation():
    text = _render_config_yaml(
        _draft("Foo: Bar", url="https://x.test/?a=1&b=2"),
        [_draft("Acme #1"), _draft("Null")],
        "US", 2840, "en",
    )
    config = _config_from_dict(yaml.safe_load(text))

    assert config.own_brand.name == "Foo: Bar"
    assert config.own_brand.url == "https://x.test/?a=1&b=2"
    assert [b.name for b in config.competitors] == ["Acme #1", "Null"]


def test_the_generated_config_keeps_its_explanatory_comments():
    text = _render_config_yaml(_draft("Acme"), [_draft("Globex")], "US", 2840, "en")

    assert "# Generated by `sos init`" in text
    assert "# Set `ambiguous: true`" in text


def test_yaml_scalar_leaves_ordinary_values_unquoted():
    assert _yaml_scalar("acme") == "acme"
    assert _yaml_scalar("Foo: Bar").startswith(("'", '"'))


# --------------------------------------------------------------------------
# `sos init` — multiple keywords per brand
# --------------------------------------------------------------------------


def test_every_collected_keyword_reaches_the_config():
    """The whole point of the keyword pass: sub-brands and products survive."""
    text = _render_config_yaml(
        _draft("Solventum", ["solventum", "littmann", "tegaderm"]),
        [_draft("Baxter", ["baxter", "baxter healthcare"])],
        "US", 2840, "en",
    )
    config = _config_from_dict(yaml.safe_load(text))

    assert config.own_brand.keywords == ["solventum", "littmann", "tegaderm"]
    assert config.competitors[0].keywords == ["baxter", "baxter healthcare"]


def test_the_ambiguous_flag_survives_the_prompt():
    text = _render_config_yaml(
        _draft("Acme"), [_draft("Emma", ["emma mattress"], ambiguous=True)], "US", 2840, "en"
    )
    config = _config_from_dict(yaml.safe_load(text))

    assert config.ambiguous_brands == ["Emma"]


def test_keywords_needing_quotes_survive_the_round_trip():
    """Keywords go through the same YAML-scalar path as brand names."""
    text = _render_config_yaml(
        _draft("Acme", ["acme", "acme: the sequel", "acme #1", "yes"]),
        [_draft("Globex")],
        "US", 2840, "en",
    )
    config = _config_from_dict(yaml.safe_load(text))

    assert config.own_brand.keywords == ["acme", "acme: the sequel", "acme #1", "yes"]


@pytest.mark.parametrize(
    "raw,expected",
    [
        ("littmann, tegaderm", ["littmann", "tegaderm"]),
        ("  Littmann ,TEGADERM ", ["littmann", "tegaderm"]),
        ("", []),
        ("   ", []),
        ("a,,b", ["a", "b"]),
        ("one\ntwo", ["one", "two"]),
    ],
)
def test_keyword_entry_is_forgiving_about_spacing_and_case(raw, expected):
    assert _split_keywords(raw) == expected


# --------------------------------------------------------------------------
# Keyword parity
# --------------------------------------------------------------------------


def test_a_thinly_covered_brand_is_flagged():
    warnings = keyword_parity_warnings({
        "Acme": ["acme", "acme app", "acme login", "acme pro", "acme cloud", "acme x"],
        "Globex": ["globex"],
    })

    assert len(warnings) == 1
    assert "Globex" in warnings[0]


def test_comparable_coverage_is_not_flagged():
    assert keyword_parity_warnings({
        "Acme": ["acme", "acme app"],
        "Globex": ["globex"],
    }) == []


def test_parity_needs_two_brands_to_compare():
    assert keyword_parity_warnings({"Acme": ["a", "b", "c", "d"]}) == []


def test_duplicate_keywords_do_not_inflate_a_brands_coverage():
    assert keyword_parity_warnings({
        "Acme": ["acme"] * 9,
        "Globex": ["globex"],
    }) == []


# --------------------------------------------------------------------------
# Date handling
# --------------------------------------------------------------------------


def test_the_current_month_is_never_requested():
    """Google Ads has no data for a month that hasn't finished."""
    assert last_complete_month(date(2026, 8, 1)) == date(2026, 7, 1)
    assert last_complete_month(date(2026, 8, 31)) == date(2026, 7, 1)
    assert last_complete_month(date(2026, 1, 15)) == date(2025, 12, 1)


def test_shift_months_crosses_year_boundaries():
    assert shift_months(date(2026, 1, 1), -1) == date(2025, 12, 1)
    assert shift_months(date(2026, 1, 1), -13) == date(2024, 12, 1)
    assert shift_months(date(2025, 12, 1), 1) == date(2026, 1, 1)
    assert shift_months(date(2026, 7, 1), -47) == date(2022, 8, 1)


# --------------------------------------------------------------------------
# Time frame selection
# --------------------------------------------------------------------------


def _range(tmp_path, config, **kwargs):
    """Resolve a request range with prompting off, as a script would."""
    options = dict(
        empty_store=True, backfill=False, months=None, date_from=None,
        date_to=None, refresh_last=None, no_prompt=True,
    )
    options.update(kwargs)
    return _resolve_range(tmp_path, config, **options)


def test_months_flag_asks_for_exactly_that_many(tmp_path, sample_config):
    start, end, reason = _range(tmp_path, sample_config, months=12)

    assert shift_months(start, 12) == shift_months(end, 1)   # 12 months inclusive
    assert "12" in reason


def test_months_flag_is_rejected_below_one(tmp_path, sample_config):
    with pytest.raises(click.ClickException, match="--months must be at least 1"):
        _range(tmp_path, sample_config, months=0)


def test_explicit_dates_beat_the_months_flag(tmp_path, sample_config):
    start, _, reason = _range(tmp_path, sample_config, months=12, date_from="2024-03")

    assert start == date(2024, 3, 1)
    assert reason == "explicit range"


def test_a_first_pull_backfills_when_nobody_can_be_asked(tmp_path, sample_config):
    """A piped or CI run must not block on a prompt nobody can see."""
    start, end, reason = _range(tmp_path, sample_config)

    assert shift_months(start, BACKFILL_MONTHS) == shift_months(end, 1)
    assert "auto-backfill" in reason


def test_the_prompt_is_suppressed_without_a_terminal(tmp_path, sample_config, monkeypatch):
    monkeypatch.setattr("sos.cli._prompt_timeframe", _unreachable)
    monkeypatch.setattr(sys.stdin, "isatty", lambda: False)

    _range(tmp_path, sample_config, no_prompt=False)   # must not raise


def _unreachable(*args, **kwargs):
    raise AssertionError("the timeframe prompt should not have been reached")


def test_no_month_before_the_last_complete_one_is_ever_requested(tmp_path, sample_config):
    _, end, _ = _range(tmp_path, sample_config, date_to="2099-01")

    assert end == last_complete_month()


# --------------------------------------------------------------------------
# `sos refresh` — the code-update step
# --------------------------------------------------------------------------
#
# These run against real throwaway repositories rather than mocks. What's
# under test is how git actually behaves — whether a dirty tree blocks a
# fast-forward, what a missing upstream does — and a mock would only assert
# our assumptions back at us.


def _run_git(cwd: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(cwd), *args], capture_output=True, text=True, check=True)


def _repo(path: Path) -> Path:
    """A git repository with one commit, shaped like an install checkout."""
    path.mkdir(parents=True, exist_ok=True)
    _run_git(path, "init", "-q")
    _run_git(path, "config", "user.email", "test@example.invalid")
    _run_git(path, "config", "user.name", "Test")
    (path / "pyproject.toml").write_text('[project]\nname = "sos"\n', encoding="utf-8")
    _run_git(path, "add", "-A")
    _run_git(path, "commit", "-qm", "first")
    return path


def _clone(origin: Path, into: Path) -> Path:
    subprocess.run(
        ["git", "clone", "-q", str(origin), str(into)], capture_output=True, text=True, check=True
    )
    return into


def test_a_non_editable_install_has_no_checkout_to_update(tmp_path, monkeypatch):
    """site-packages has no repository above it, so there's nothing to pull."""
    package = tmp_path / "site-packages" / "sos" / "__init__.py"
    package.parent.mkdir(parents=True)
    package.write_text("", encoding="utf-8")
    monkeypatch.setattr(sos, "__file__", str(package))

    assert _source_checkout() is None


def test_the_checkout_is_found_from_the_code_not_the_cwd(tmp_path, monkeypatch):
    """Resolving from the package is what stops a refresh pulling someone
    else's project just because that's the directory they happened to be in."""
    root = _repo(tmp_path / "checkout")
    package = root / "src" / "sos" / "__init__.py"
    package.parent.mkdir(parents=True)
    package.write_text("", encoding="utf-8")
    monkeypatch.setattr(sos, "__file__", str(package))
    monkeypatch.chdir(tmp_path)

    assert _source_checkout() == root.resolve()


def test_uncommitted_changes_stop_the_update(tmp_path):
    root = _repo(tmp_path / "repo")
    (root / "pyproject.toml").write_text("edited by hand", encoding="utf-8")

    safe, why = _pull_status(root)

    assert safe is False
    assert "uncommitted" in why


def test_a_clean_checkout_is_safe_to_update(tmp_path):
    safe, why = _pull_status(_repo(tmp_path / "repo"))

    assert (safe, why) == (True, "")


def test_no_change_is_reported_when_already_current(tmp_path):
    clone = _clone(_repo(tmp_path / "origin"), tmp_path / "clone")

    changed, message = _pull(clone)

    assert changed is False
    assert "up to date" in message


def test_a_moved_upstream_reports_a_change_and_lands_the_files(tmp_path):
    origin = _repo(tmp_path / "origin")
    clone = _clone(origin, tmp_path / "clone")

    (origin / "new.txt").write_text("something new", encoding="utf-8")
    _run_git(origin, "add", "-A")
    _run_git(origin, "commit", "-qm", "second")

    changed, message = _pull(clone)

    assert changed is True
    assert "updated" in message.lower()
    assert (clone / "new.txt").read_text(encoding="utf-8") == "something new"


def test_a_failed_update_is_reported_rather_than_raised(tmp_path):
    """Offline, or no upstream configured: the data refresh must still go ahead."""
    changed, message = _pull(_repo(tmp_path / "repo"))   # no remote at all

    assert changed is False
    assert "couldn't update the code" in message


def test_the_restart_guard_stops_a_second_update(monkeypatch):
    """One restart, never two — the guard is what bounds the recursion."""
    monkeypatch.setenv(REEXEC_ENV_VAR, "1")
    monkeypatch.setattr("sos.cli._source_checkout", _unreachable)

    _update_code()   # must return without looking for a checkout at all
